### ISSUE TITLE
[BUG] must check `not null` when validating `object` type

### ISSUE THREAD

**Issue by samchon** [GoogleFeud/ts-runtime-checks#11]
**Describe the bug**
```javascript
typeof null === "object" // true
```

When checking object type, you have to check `not null` at the same time.

**Playground link**
https://googlefeud.github.io/ts-runtime-checks/

**Expected behavior**
Check not null at the same time

**Comment by GoogleFeud** [comment]
Good catch! I'll update the library soon and fix this!

**Comment by samchon** [comment]
@GoogleFeud This bug has been in website (https://[googlefeud.github.io/ts-runtime-checks/](https://googlefeud.github.io/ts-runtime-checks/)).

However, it still occurs in NPM package.
