### ISSUE TITLE
[TEST] List of test types for testing

### ISSUE THREAD

**Issue by samchon** [GoogleFeud/ts-runtime-checks#18]
Hello, I'm develper of [typia](https://github.com/samchon/typia), and came again.

It was really amazing for me that, you've succeed to build a playground website even containing transformation. In `typia` case, I had provided [StackBlitzs](https://stackblitz.com/github/samchon/typia-playground?view=editor&file=src%2Findex.ts) link for a long time. Looking at your amazing playground website, I decided to study and follow your playground website in my `typia` project.

Instead, I wrote bug reporting issues, that `ts-runtime-checks` had to fix urgently. Also, I'll provide test type set that I'm using. Thanks for making such interesting repo, and hope your library to be much stable and evolved. I hope such transformation libraries to be much famous and spread to the world widely.

https://github.com/samchon/typia/tree/master/test/structures

**Comment by GoogleFeud** [comment]
> Instead, I wrote bug reporting issues, that ts-runtime-checks had to fix urgently. Also, I'll provide test type set that I'm using. Thanks for making such interesting repo, and hope your library to be much stable and evolved. I hope such transformation libraries to be much famous and spread to the world widely.

Thank you so much for the issues you created, helped me a bunch with creating the current version (0.2.0)!

> It was really amazing for me that, you've succeed to build a playground website even containing transformation. In typia case, I had provided [StackBlitzs](https://stackblitz.com/github/samchon/typia-playground?view=editor&file=src%2Findex.ts) link for a long time. Looking at your amazing playground website, I decided to study and follow your playground website in my typia project.

Yeah, feel free to borrow anything from this repository!
