### ISSUE TITLE
ExactProps does not throw for additional nested props

### ISSUE THREAD

**Issue by mmamedel** [GoogleFeud/ts-runtime-checks#2]
**Describe the bug**
The `ExactProps` type does not cause code to throw on additional nested props.

**Playground link**
[Link](https://googlefeud.github.io/ts-runtime-checks/?code=FAehAIEkDsBcFMBOBDAxrAlgN3uADgDbICeA5ogPYCu0AJgITgDqiGC4G04x1i4qFWrmR1wAZ3i424UvFiZopcLBTQxeDAXi1wFLrAAWuLQDNY9YJwSITaXAFUJfAN7Bw78NGQBbeAC5xFU5SABo3DwxaAOgqbwAjJHD3aHgxBCjwVw9szx9-QNZFAG4knMjo2ITEEuyAX2B64BMadAw9cCxkAkjkBAAKKicAgEExJ1gAHgBRAA80WAAFSjwxCcckAD4NgEpM0sQ5KkQuAAMAEQpUzwpYZQNKAHdwEwo+ACIAEmcBpwA6FLS2nAyDEwOgxG2v2QtFobDaXgItTeJwawGAnW6tF68D6WQ8Xl8AQA5AT4ESwtlyuAAIwU-GpdIBPE5XKE8AkvLk0qUjIAJjpLOhsMwei6xKFcNFBA6XSoZNK9VqwNBIghQA)

**Expected behavior**
I was expecting `ExactProps` to throw if there was any additional props, not matter if they are nested or not.
But this may be a new functionality of a `Strict` type.

**Comment by mmamedel** [comment]
That's cool! When you push this to the library I'll add it to the benchmark. As a matter of speed, so far it is the fastest 😮

**Comment by GoogleFeud** [comment]
Just released a new version, `ExactProps` is now recursive by default!

**Comment by mmamedel** [comment]
Cool, I have sent a new pr with the updated version: https://github.com/moltar/typescript-runtime-type-benchmarks/pull/931
