### ISSUE TITLE
[BUG] Generated code has top comment copied to several locations

### ISSUE THREAD

**Issue by FredTreg** [GoogleFeud/ts-runtime-checks#26]
**Describe the bug**
While trying to tackle another bug with the playground, I stumbled upon this minor issue: a large comment located at the top of the playground gets copied to several locations of the generated code (see linked playground)

**Playground link**
[playground](https://googlefeud.github.io/ts-runtime-checks?code=PTAEBUAsEsGdQMYHsC2KCmA7ALgKBKAObrbzIAO06AJvmNkqAO7rQBO1oANkggIbZoSTLFy5sAT3LpQAGV4ChmAMro+bBJABi0LtnRsAIg1ABeUAG9coUADddXPsQCS1AFyhnOUADJQmAFcUACMDa1A+TCRsSANXDy9sX38g0LZwiRIAQSiYuPdPbz9AkLCAXzEAMwDMBEFhUFiuHgAKYKRqCQ95fnqVNQ1tXX0jBgBKS3CbZBEk4LNQds6I+CzYWANsAB4exWFVdU0dPQNjJAA+XDKgA)

**Expected behavior**
Comment does not make it to the generated code?

**Additional context**
0.3.1

**Comment by GoogleFeud** [comment]
It's a bizarre issue... I'm pretty sure it also existed when the transpiled code wasn't shown in a separate monaco editor. I can't replicate it in a local environment either.

**Comment by FredTreg** [comment]
Simpler [playground](https://googlefeud.github.io/ts-runtime-checks?code=PTAEBUAsEsGdQMYHsC2KCmA7ALgKBKAObrbzIAO06AJqNkqAIagDu60ATrQDZIKPZoSTLlzYAnuXSgAkgDlwoALyycoAGShMAVxQAjdB1ESpoADJ8BQzAGV0jDgkgAxaN2yGAIvWWgA3rigoABubtyMxDLUAPwAXLIKoAA+Wtrc3LgAvrgAZtqYCILCoJDo6UgAFHpI1OLxFvxFtvaOLm4eHN5IAJT+gUGIwrDYoHq+1bVM8ACCsLCG2AA8DVbCdg5Oru5e9AB8WaJAA) in case you want to tackle the issue. Or I can close it...
