### ISSUE TITLE
[BUG] Infer & check not works properly

### ISSUE THREAD

**Issue by SirReiva** [GoogleFeud/ts-runtime-checks#34]
Infer and check don't work correctly with generic parameters, create a union type instead of comparing separately

**Playground link**
[playground](https://googlefeud.github.io/ts-runtime-checks/?code=JYOwLgpgTgZghgYwgAgKoGdrIN4ChnIhwC2EAXMumFKAOYDc+ywAJhSAK7EBG0jAvrlCRYiFAFFicYABscTbgHsWATwpUaIBkzCL11OgNy4EikFWQtFAYQAWEBAGtkAXmQAeACoA+ABQs4MDgKDhBHEEUAdxAASgpPZAAfQg4ZORdveQJTczBkAG0oCHQAGmRoKEUodABdV2QEeyd3AEkQGGgvbz8AoJjGAmAYZF8KqvQAOhkILTBbZEyABhisggazdEVpqcVaUahK6v6mAiKwDigQFLSB5EFTiHPL5CL0AUYTDbywABFAuHqeAIRFIFAARCx0HAYOgWGCSkxWBQAKwI-gfHKbbYyXb+GxNRzuDDQPy-f4xY6YrYQHZ7Kx2ByEyTSGSkv59fpAA)

![Captura de pantalla 2023-08-25 160743](https://github.com/GoogleFeud/ts-runtime-checks/assets/50754871/caf61543-bd8b-4698-acbd-1af86de6aa49)

**Comment by GoogleFeud** [comment]
Hi! Currently, this library isn't the best at handling unions of objects/arrays, This will be looked at very soon, but for now, you could create a discriminated union out of the objects and it should work fine - [playground](https://googlefeud.github.io/ts-runtime-checks?code=JYOwLgpgTgZghgYwgAgKoGdrIN4ChnIhwC2EAXMumFKAOYDc+ywAJhSAK7EBG0jBAa1BtkAIg6YooxgF9coSLEQoAosTjAANjibcA9iwCeFKjRAMmYPSep1+yISBGiI6rdNxzcCPSCrIWPQBhAAsIBAFkAF5kAB4AFQA+AAoWODA4Cg4QARA9AHcQAEoKeOQAH0IOTW0oxJ0CHz8wZABtKAh0ABpkaCg9KHQAXWjkBDCI2IBJEBhoBMSUtIyi+2AYZGS+gfQAOk0IczAQ5HqABiKGgjHfdD0D-b1aLah+wdWmAg6wDigQKpq9jkXwgPz+yA66FkjG8txaYAAIuk4KM8AQiKQKKIWOg4DB0CxRF0mKwKABWYkyGFNO4PTRPVLBCYCWIYaApRHIoofGn3CCPZ6BULhFlqDSaDlIlarIA)
