### ISSUE TITLE
[BUG] Namespace 'ts' has no exported member 'TypeMapper'

### ISSUE THREAD

**Issue by samchon** [GoogleFeud/ts-runtime-checks#35]
The type `ts.TypeMapper` is `@internal` tagged type.

Therefore, when install `ts-runtime-checks` in the user side, it becomes a compiler error like bleow:

```bash
node_modules/ts-runtime-checks/dist/gen/validators/genValidator.d.ts:6:16 - error TS2694: Namespace 'ts' has no exported member 'TypeMapper'.
```

**Comment by GoogleFeud** [comment]
This library uses `@types/ts-expose-internals` in order to use internal types, you can fix this in two ways:
- Add `"@types/ts-expose-internals": "npm:ts-expose-internals@^5.1.5"` to your dev dependencies
- Set the `skipLibCheck` option in the `tsconfig.json` file to `true`

**Comment by samchon** [comment]
I mean that this bug occured when installing and using `ts-runtime-checks`.

It should be fixed for users.

**Comment by GoogleFeud** [comment]
The transformer has to use these internal properties/methods in order to function so there isn't much that can be done except using `@ts-ignore` instead of the package. 

Setting `skipLibCheck` to true is almost always a good idea, anyways.
