### ISSUE TITLE
[BUG] Adding null as an alternative for a type does not produce any check code

### ISSUE THREAD

**Issue by FredTreg** [GoogleFeud/ts-runtime-checks#38]
**Describe the bug**
Check the playground below, you can see that this code:
```
type OptionalFolderName = string | null
const folder1 = 'root1'
const valid1 = folder1 as Assert<OptionalFolderName>
```
does not emit validation code at all when it should

**Playground link**
[playground](https://googlefeud.github.io/ts-runtime-checks?code=C4TwDgpgBAsghgOwCZ2AewE4gGJoDZIQYBycAttALxQDOwGAlggOYBQokUA8mMA2gjh5cBIqQpRqdRiygAfKAgCuePK1YBjAXSgAzfIQwAGSVADkGNGmBGzm7cD0GiARlMWrwF3fsIdANyEGJBNqfVFjKDgaKABBGhoiYAAeeGRUTBxnEnIIAD5fAKCkNzDst2i4hKTknj4BIRFDcXz1IA)

**Expected behavior**
`Assert` should produce validation code

**Additional context**
The problem does not occur when checking a field of an object, this seems to occur only when the variable is top-level.

**Comment by GoogleFeud** [comment]
Will be fixed in the next patch!
