### ISSUE TITLE
[BUG] Resolve strange behavior

### ISSUE THREAD

**Issue by dyushin** [GoogleFeud/ts-runtime-checks#46]
Let's look at this code fragment from [playground](https://googlefeud.github.io/ts-runtime-checks/?code=MYewdgzgLgBAZjAvDAPAFQHwAoBuBDAGwC4YBBCCAUwCcoUAlSiEAnS9DDASiQxgG8AUAEhqlKAFdqYGPgKCAvoMGhILSgDoCIAOZY4KfjDB4AtpRIAjEOrwyF2I3IkWBxs64BEASXxhPMAqBMHgQIWAAnlxcKuDMBJraegZGJuYkYBKmljSBjrKELiSpHiRQ1C7BQaHhUTFAA)
```
const f = <T>(val: Assert<Resolve<T>>) => {
	return val
}

console.log(f<{ name: boolean }>({ value: { name: "Ivan" } } as any))
console.log(f<{ name: number }>({ value: { name: true } } as any))

```

after tranpilation we get this code

```
const f = (val) => {
    return val;
};
console.log((() => {
    const val = { value: { name: "Ivan" } };
    if (typeof val !== "object" || val === null)
        throw new Error("Expected val to be an object");
    if (typeof null.name !== "boolean")
        throw new Error("Expected .name to be a boolean");
    return f(val);
})());
console.log((() => {
    const val = { value: { name: true } };
    if (typeof val !== "object" || val === null)
        throw new Error("Expected val to be an object");
    if (typeof null.name !== "boolean")
        throw new Error("Expected .name to be a boolean");
    return f(val);
})());
```
There are 2 problems:
1) `null.name` instead of `val.name` but i have already created [issue](https://github.com/GoogleFeud/ts-runtime-checks/issues/45) with this bug
2) in both console.log we see "Expected .name to be a boolean", but `name` in second function expected to be a number, not boolean. It seems that the compiler only considers the first function call and copies it to the others

**Comment by GoogleFeud** [comment]
Thanks for the bug report, will be fixed very soon!

**Comment by zeeeeby** [comment]
Hi! 
Thanks for the quick fixes
Can I ask when the package is scheduled for release?

**Comment by dyushin** [comment]
Hi! 
Thanks for the quick fixes
Can I ask when the package is scheduled for release?

**Comment by GoogleFeud** [comment]
Hi, I've been quite busy, a new version will be released before Christmas for sure!
