### ISSUE TITLE
[BUG] Custom error imports are erased at compilation causing runtime errors

### ISSUE THREAD

**Issue by FredTreg** [GoogleFeud/ts-runtime-checks#47]
**Describe the bug**
When using the construct `Assert<type, ThrowError<MyInputError>>` the` import { MyInputError } from 'somewhere'` statement gets removed at compilation time.

Generated code will fail with `MyInputError is not defined` at runtime.

**Playground link**
Compare this [playground](https://googlefeud.github.io/ts-runtime-checks/?code=FASwtgDg9gTgLgAgN4IJIDsIFc4FEYywC+CAZoWAgOSlRRXDAD0TAxlOgM6ICmBCAXgToeAdzSYc+QjAAUASkYh0cPqQCGrHggCqnPsmAJjCEABMAXMKxgARnyMn06sDyvcYygOYAaYEUZSLHRWOBAOBAA3dQAbc3VVWSx9GCsAQU4UuAAePT4fBAAVAAtCUWlYbIxsPAJYAD56+UMTBBYEAE0oLBgEdjMeADph-0ZouLMEnlkUZ1crACJ1W1YFgvMrABYEInkAbmAgA) and this [playground](https://googlefeud.github.io/ts-runtime-checks?code=FASwtgDg9gTgLgAgN4IJIDsIFc4FEYywC+CAZoWAgOSlRRXDADGU6AzogKYEIC8C6TgHc0mHPkIwAFAEpGIdHG6kAhk04IAqm27JgCAwhAATAFwCsYAEbd9h9CrCdzHGAoDmAGmBFGpLOhMcCCsCABuKgA2JipKUlg6MOYAgmyJcAA82tyeCAAqABaEQhKwGRjYeASwAHw1MnqGCAD0zQgAmlBYMAgsxpwAdEM+jBHRxrGcUigOTuYARCpWTPO5JuYALAhEMgDcwEA)

In the first playground, you can see the import being removed, in the second playground it remains because the `InputError` class is used directly at line 4: this is the current workaround I found to make it work.

**Expected behavior**
One can use custom error classes when using `Assert` without having to create fake statements.

**Additional context**
* ts-runtime-checks: 0.4.1
* typescript: 5.2.2 (ESM)

**Comment by GoogleFeud** [comment]
This issue turned out to be more difficult than I thought, it will be resolved, but maybe in the next patch. There are two ways to fix this error:

Turn on the `verbatimModuleSyntax` [typescript options](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) (5.0 and up, only works with CommonJS)

Or using require directly:
```ts
import { MyError } = require("./path");
```
