### ISSUE TITLE
[FEATURE] tests with jest

### ISSUE THREAD

**Issue by dyushin** [GoogleFeud/ts-runtime-checks#49]
Hello!

I want to run the tests with jest, but encountered an error

`TypeError: (0 , ts_runtime_checks_1.check) is not a function or its return value is not iterable
`
I can't combine ts-jest with tspc

Is there any way to combine them?

**Comment by dyushin** [comment]
Found solution

just change compiler in jest.config file

```
module.exports = {
	globals: {
		"ts-jest": {
			tsconfig: "tsconfig.json",
			compiler: "ts-patch/compiler",
		},
	},
```

**Comment by dotnich-io** [comment]
@dyushin do you know why that works, and can you explain that to me please?

**Comment by zeeeeby** [comment]
> @dyushin do you know why that works, and can you explain that to me please?

I don't know exactly how. But it seems that, as in the case of the ts-runtime-checks library itself, the code is compiled by a modified ts-patch before running the tests

**Comment by dyushin** [comment]
> @dyushin do you know why that works, and can you explain that to me please?

I don't know exactly how. But it seems that, as in the case of the ts-runtime-checks library itself, the code is compiled by a modified ts-patch before running the tests
