### ISSUE TITLE
Expand typescript types

### ISSUE THREAD

**Issue by mmamedel** [GoogleFeud/ts-runtime-checks#5]
**Is your feature request related to a problem? Please describe.**
This library has great performance and a lot of potential but I see it also will face some limits: Typescript types are not so detailed as some other schema libraries can be. Just for example: With typescript you may say this:
```ts
interface Person {
  name: string,
  age: number,
}
```
But you can't limit the length of the string or the age to always be an integer.
I see that we have here `Range` for checking a specific parameter and we `Expr` which give user a lot of power... but I wonder if at some point a more declarative API would make it easier.

**Describe the solution you'd like**
I was thinking of something like this:
```ts
interface Person {
  name: Str<{ max: 100 }>,
  age: Num<{ min: 0, max: 50 }>,
}
```
For typescript `Str` would still be a `string` and `Int` a `number`. But if user uses the `Assert`, `is` or any other of this library functions it would add validations in build time.
An this kind of helper types would be optional, just if users really wanted to expand TS types.

**Describe alternatives you've considered**
The other way I have seen this been done is with decorators in libraries such as class-validator. The problem is that you can only use the decorators within classes and users have to enable validator usage...
I feel like the type route matches more this library solution style.

**Comment by GoogleFeud** [comment]
I like this a lot - I'll replace `Match` and `Range` with more general types which have different options, like your example. `string` and `number` will still work, though!

**Comment by mmamedel** [comment]
Yeah, there is a big range of options we can add later to these generic types:
# Str
## Base
- min: min number of characters
- max: max number of characters
- length: exact number of characters
- regex: check against regex
## Future additional
- uuid: should check if it is a uuid (predefined regex)
- email: should check if it is an email (predefined regex)
- url…
- startsWith…
- endsWith…
- and many other examples from validator.js

# Num
## Base
- min/gte: min value >=
- max/lte: max value <=
- gt: greater >
- lt: lower <
- multipleOf: checks 

## Additional
- int: it is an integer
- positive: > 0
- negative: < 0
- nonpositive: <= 0
- nonnegative: >= 0


Other possible types:
- Date: with min, max to validate dates
- Enums: do we support them?
- Arrays: with min, max and length

**Comment by GoogleFeud** [comment]
Added most of your suggestions :). For some like `multipleOf`, `startsWith`, `endsWith`, etc. users can use the `If` type, here's an [example](https://googlefeud.github.io/ts-runtime-checks/?code=FAFwngDgpgBAyiAhgJxAZwOoEsQAsA8AKrlgHYDmMUAHiFKQCZoxojJnkB8MAvDAJIAzfK3YUANDAAGAEjRQANoIB0rFOmx4AFAB0ARDIDexDgF99ASimS2AVyicA3MAD0LgaTrJEAYxBYAN1gIBUQwcmQAe1tGAEIYDHY6GDIYMGjkGB9IhlhERhYoWBwYcigQfwoYNny0CCwFKAYYSNJq3FhGwRBY4DIvQV9YAFV5TMNgGCmYUkQAWygALhY2DnFJ6awGZYR1TBwCPQAJRQVIvU5gU2BgQRi-LFaYAMQFLcQ6LVsx5YBBNDGIHwoygyE4FhgE2mMDcMAAmhksjkoMpUVdgEA)
