### ISSUE TITLE
[BUG] Regression from 0.4.1 : bounds are no longer included when checking for string size (or number Min/Max)

### ISSUE THREAD

**Issue by FredTreg** [GoogleFeud/ts-runtime-checks#51]
**Describe the bug**
When checking that a string should have a MinLen of 2, then the string "en" should be allowed

**Playground link**
[Playground](https://googlefeud.github.io/ts-runtime-checks?code=FAehAIEkDsBcFMBOBDAxrAlgN3uADgDbICeA5ogPYCu0AJgITgDqiGC4G04x1i4qFWrmR1wAZ3i424UvFiZopcLBTQxeDAXi1wFLrAAWuLQDNY9YJwSITaXAFUJfAN7Bw78NGQBbeAC5xFU4lADJwAFlOABl4aAAeACYAPgAaNw8MWgDoKm8AIyRwMMj4gEYABiTgAF9gExp0DD1wLGQCTOQEAAoqJwCAQTEnWDjHJCSASnBXWuBW9tpO+C7nTx9-cAAiWM2UjizwCvBqiYBuYCA)

**Expected behavior**
As one can see in the playground, the code:
```
interface User {
    name: string & MinLen<2>,
    id: number & Min<10>
}
function validate(user: Assert<User>) {
}
```
produces the following checks:
```
if (typeof user.name !== "string" || user.name.length <= 2)
  throw new Error("Expected user.name to be a string, to have a length greater than 2");
if (typeof user.id !== "number" || user.id <= 10)
  throw new Error("Expected user.id to be a number, to be greater than 10");
```
when it should produce
```
if (typeof user.name !== "string" || user.name.length < 2)
  throw new Error("Expected user.name to be a string, to have a length greater than 2");
if (typeof user.id !== "number" || user.id < 10)
  throw new Error("Expected user.id to be a number, to be greater than 10");
```
i.e. `<`instead of `<=`

**Additional context**

 * This used to work in `0.4.1` so going back to this version for now. A unit test is probably missing somewhere.
 * It is the same for `Max<>` and `MaxLen<>`
 * Versions: ts-runtime-checks: 0.4.2, typescript: 5.3.3 (ESM)

**Comment by GoogleFeud** [comment]
It was always intended for the `Min` and `Max` utility types to be non-inclusive, so `Min<1> & Max<10>` would be a number in the range `(1, 10)`, however there was a bug with how expressions were negated that got fixed in the last patch and now the types are generating the intended code.

The bug has existed for quite a while so I guess the best thing to do is to make them inclusive in the next patch!

**Comment by FredTreg** [comment]
Yes, please do, for me it would feel weird to say that the maximum length authorized for a string is 10 and at the same time to not authorize a string of length 10.
