### ISSUE TITLE
Request: Full examples?

### ISSUE THREAD

**Issue by douglasg14b** [GoogleFeud/ts-runtime-checks#67]
Examples seem to omit the imports, and imports like `import { is } from 'ts-runtime-checks';` don't work since items like `is` are not exported/provided by `ts-runtime-checks` after build time 🤔 

> import { is } from 'ts-runtime-checks';
>         ^
> SyntaxError: The requested module 'ts-runtime-checks' does not provide an export named 'is'

**Comment by GoogleFeud** [comment]
Hi, sorry for the late response! Are you sure you're [using the library correctly](https://github.com/GoogleFeud/ts-runtime-checks?tab=readme-ov-file#usage)? You have to use one of the packages listed to transform the typescript code

**Comment by douglasg14b** [comment]
It's been a long time since then, opted to not use the lib. Might revisit another year if the need arises.

Closing.
