### ISSUE TITLE
Enable use of generics

### ISSUE THREAD

**Issue by mmamedel** [GoogleFeud/ts-runtime-checks#7]
**Is your feature request related to a problem? Please describe.**
When using generics, the library doesn't resolve the type provided. Like in:
```ts
import { RequestHandler } from 'express';
import { ParamsDictionary } from 'express-serve-static-core';
import { check } from 'ts-runtime-checks';

type ErrorListItem = { type: 'Query' | 'Params' | 'Body'; errors: string[] };

const sendErrors: (errors: Array<ErrorListItem>, res: Response) => void = (errors, res) => {
  return res.status(400).send(errors.map((error) => ({ type: error.type, errors: error.errors })));
};

const validateRequestBody: <TBody>() => RequestHandler<ParamsDictionary, any, TBody, any> = () => (req, res, next) => {
  const [_, errors] = check<TBody>(req.body);
  if (!errors.length) return next();
  return sendErrors([{ type: 'Body', errors }], res);
}
```

Library transpiles `validateRequestBody` to something like:
```js
const validateRequestBody = () => {
  return (req, res, next) => {
    const _ = req.body;
    const errors = [];
    if (typeof _ !== "object")
      errors.push("Expected _ to be TBody.");
    if (!errors.length)
      return next();
    return sendErrors([{ type: 'Body', errors }], res);
  };
};
``` 

**Describe the solution you'd like**
The problem seem complex because the type is being defined somewhere else, not in the function using `check`. So I wonder if in case of a generic being used the function could wrap the validation coming from source, like:

```js
const validateRequestBody = (checkFn) => () => {
  return (req, res, next) => {
    const [_, errors] = checkFn(req.body);
    if (!errors.length)
      return next();
    return sendErrors([{ type: 'Body', errors }], res);
  };
};

api.get('/', validateRequestBody((value) => {
  const errors = [];
  // validation
  return [value, errors]
})(), (req, res) => {
  // request handler
})
``` 

**Describe alternatives you've considered**
The only alternative in this specific case is writing the middleware for each case like:
```ts
api.get('/',
  (req, res) => {
    const [_, errors] = check<MyRequestType>(req.body);
    if (errors.length)
      return res.status(400).send(errors);
  },
  (req, res) => {
  // request handler
})
```

**Additional context**
This is one example of where I would see generics. Just here I would seek to expand to also have Params and Query validation. But you probably would think of many more ways to use this.

**Comment by GoogleFeud** [comment]
This would be very difficult to pull off, the only easy solution that comes to my mind is to create a different function for each type:
```ts
function func<T>(a: unknown) {
   const [, errors] = check<T>(a);
  // other code...
}

func<string>("abc");
func<number>(123);
```
will transpile to:
```js
function func_1(a) {
    const errors = [];
     if (typeof a !== "string") errors.push(...);
     // other code...
}

function func_2(b) {
  const errors = [];
  if (typeof a !== "number") errors.push(...);
  // other code...
}

func_1("abc");
func_2(123);
```
but that could increase the file size of the javascript files by a lot. Personally I think it would be a nice feature to have but I'm not sure if it's worh it.

**Comment by GoogleFeud** [comment]
Implemented in 0.2.0

**Comment by danehansen** [comment]
im having trouble wring reusable code for this library, which i suspect is related to this issue. heres a couple functions i have, which are mostly the same so i would like to consolidate them:
```
type EndpointAResponse = {
  status: string;
  item: {id:string};
}
function checkEndpointAResponse(
  response: EndpointAResponse,
): EndpointAResponse {
  try {
    ((r: Assert<ExactProps<EndpointAResponse>>) => true)(response);
  } catch (err) {
    console.warn("endpointA response type mismatch:", {
      response,
      error: err,
    });
  }
  return response;
}

type EndpointBResponse = {
  status: string;
  items: {id:string}[];
}
function checkEndpointBResponse(
  response: EndpointBResponse,
): EndpointBResponse {
  try {
    ((r: Assert<ExactProps<EndpointBResponse>>) => true)(response);
  } catch (err) {
    console.warn("endpointB response type mismatch:", {
      response,
      error: err,
    });
  }
  return response;
}
```
these work. but i have a lot of these endpoints to look at. i would like to use a function like this, but it doesn't work:
```
function checkResponse<T>(
  response: T,
): T {
  try {
    ((r: Assert<ExactProps<T>>) => true)(response);
  } catch (err) {
    console.warn("endpoint response type mismatch:", {
      response,
      error: err,
    });
  }
  return response;
}
```
what am i doing wrong?
`Type 'T' does not satisfy the constraint 'object'.`

**Comment by GoogleFeud** [comment]
> im having trouble wring reusable code for this library, which i suspect is related to this issue. heres a couple functions i have, which are mostly the same so i would like to consolidate them:
> 
> ```
> type EndpointAResponse = {
>   status: string;
>   item: {id:string};
> }
> function checkEndpointAResponse(
>   response: EndpointAResponse,
> ): EndpointAResponse {
>   try {
>     ((r: Assert<ExactProps<EndpointAResponse>>) => true)(response);
>   } catch (err) {
>     console.warn("endpointA response type mismatch:", {
>       response,
>       error: err,
>     });
>   }
>   return response;
> }
> 
> type EndpointBResponse = {
>   status: string;
>   items: {id:string}[];
> }
> function checkEndpointBResponse(
>   response: EndpointBResponse,
> ): EndpointBResponse {
>   try {
>     ((r: Assert<ExactProps<EndpointBResponse>>) => true)(response);
>   } catch (err) {
>     console.warn("endpointB response type mismatch:", {
>       response,
>       error: err,
>     });
>   }
>   return response;
> }
> ```
> 
> these work. but i have a lot of these endpoints to look at. i would like to use a function like this, but it doesn't work:
> 
> ```
> function checkResponse<T>(
>   response: T,
> ): T {
>   try {
>     ((r: Assert<ExactProps<T>>) => true)(response);
>   } catch (err) {
>     console.warn("endpoint response type mismatch:", {
>       response,
>       error: err,
>     });
>   }
>   return response;
> }
> ```
> 
> what am i doing wrong? `Type 'T' does not satisfy the constraint 'object'.`

You'll have to use either the `Resolve` or `Infer` markers, [here's an example](https://googlefeud.github.io/ts-runtime-checks/playground/?code=FAehAIHkAUBUElIDlwEYBc4DiBLAbgKbgECGAxgBbEB2AJgA4D2O1ALuLSayeCdeDloE2OAGY4CAJ1AQAyo3CsKRADY4ARpJKSAnuDJ9iJAM44Ve2mNFThZHFyJKCAWwA0i5dRngArscfK4ADk8NTWkkHgztoA1lLALKxSouREAKJ0TIkAggBKBMZM1P7gAN7A4JU0DMxsmABE2fWuFVXG3Kx+mO2SLADmLVUCSc6Y5UNDgt2svdR9rZUAvsDLCWzJqeAZNYkAQvmFjMVE41XCO3Xg9bvNC+DtXF33M-2DVTgjY3eTtNOz80NFgBtAC6K2AwFEPmoZFYOCO+mUZBiByK-gAPLBiAAPJJ0YxlapZS49frgRYAPgAFJICmiCJhoTFqIwAO7UACUZTuMz0pwm+iO7XAeBIKh8RAAvOBaYdjrwCdljP5JKx0aFwpiKRSANx3Rb6LiUcBUqSSLn8iZkIWMFQEAB0rO01Cp9XOxPYsvpih09CIzhwxmirEo6Ga3IFAq9QoIb0jZ0kkkYkkwZvtzgKxhIfVj3yqiw5esBd1pnUk-Gjxz1q0oBGRqJj6O2HrydJj1NKRNqrAaTXcD06xkwqAATABmdwfFxjAS-K4kdRkerk8mF4C1+tt45NzLd-Zb-wdruJBo3fsdJ71BdLyefcBAztTeeL5eLEGrvUQsBQOCIFAjzAAE1GB8IIVBUcAKBIQhFAUAwQyoAhCF0RQcAzCEoRhOEEQ3FEDwIEdMRxPFaAJRh1AAKzrVhqUrfxMCVFU1QOW1CC1CkLRLAgy34GYJWrL85EYDNWWUWl7QkiFrWKdhcIIWhwGlXCG2OEcqU7AdL2vcMp1GQkn1HMdyQLHUgA)
