### ISSUE TITLE
This is bad ass

### ISSUE THREAD

**Issue by mrjjwright** [GoogleFeud/ts-runtime-checks#8]
Thanks so much!

**Comment by mrjjwright** [comment]
oh let me know if you are on Twitter so I can follow you.

**Comment by GoogleFeud** [comment]
I'm glad you like the project! Yup, it all runs in the browser, and you could totally use it for your tool! The [genTranspile](https://github.com/GoogleFeud/ts-runtime-checks/blob/main/playground/utils/transpile.ts#L41) function is a good example of how to do it!
